name: Code Scan

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  backend_plugins:
    runs-on: ubuntu-latest
    env:
      PROD_ARCHIVESSPACE_VERSION: v3.3.1

    steps:
    - name: Checkout ArchivesSpace
      uses: actions/checkout@v4
      with:
        ref: ${{ env.PROD_ARCHIVESSPACE_VERSION }}
        repository: Smithsonian/archivesspace

    - name: Checkout plugin
      uses: actions/checkout@v4
      with:
        path: ${{ github.event.repository.name }}

    - name: Copy plugin to ArchivesSpace
      run: |
        cp -r ${{ github.workspace }}/${{ github.event.repository.name }} ${{ github.workspace }}/plugins
    - name: Run Rubocop
      run: |
        ./build/run rubocop -Ddir="plugins/${{ github.event.repository.name }}"
