name: Lint

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-ruby@v1
      - run: bin/rubocop -f github
