name: Lint

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      PROD_ARCHIVESSPACE_VERSION: v3.3.1
    steps:
      - name: Checkout ArchivesSpace
        uses: actions/checkout@v4
        with:
          ref: ${{ env.PROD_ARCHIVESSPACE_VERSION }}
          repository: Smithsonian/archivesspace
      - name: Run rubocop
        run: |
          gem install rubocop
          rubocop -f g
